=== Estamel/MyGitTest/out/production/day018/test05/dtd.dtd
<!ELEMENT students (student,student,teachers)>
<!ELEMENT student (id,name,age)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT teachers (teacher)>
<!ELEMENT teacher (id,name,age)>

=== Estamel/MyGitTest/day018/src/test05/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM 'dtd.dtd'>
<students>
    <student >
        <id>1</id>
        <name>张三</name>
        <age>24</age>
    </student>
    <student >
        <id>2</id>
        <name>赵四</name>
        <age>25</age>
    </student>
    <teachers>
        <teacher>
            <id>1</id>
            <name>王五</name>
            <age>66</age>
            <!--asdfdsafasdfas-->
        </teacher>
    </teachers>
</students>
